name: detectron2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.3
  - ffmpeg=4.4.1
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - icu=69.1
  - intel-openmp=2021.4.0
  - ipykernel=6.7.0
  - ipython=7.31.1
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9d
  - jupyter_client=7.1.1
  - jupyter_core=4.9.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libdeflate=1.8
  - libdrm=2.4.109
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libnsl=2.0.0
  - libpciaccess=0.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuv=1.43.0
  - libva=2.13.0
  - libvpx=1.11.0
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.6
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - prompt-toolkit=3.0.24
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pygments=2.11.2
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pyzmq=22.3.0
  - readline=8.1
  - setuptools=60.5.0
  - six=1.16.0
  - sqlite=3.37.0
  - svt-av1=0.8.7
  - tk=8.6.11
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.0.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - black==21.4b2
    - cachetools==4.2.4
    - charset-normalizer==2.0.10
    - click==8.0.3
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - detectron2==0.6+cu113
    - fonttools==4.28.5
    - future==0.18.2
    - fvcore==0.1.5.post20220119
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - hydra-core==1.1.1
    - idna==3.3
    - importlib-metadata==4.10.1
    - importlib-resources==5.4.0
    - iopath==0.1.9
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mypy-extensions==0.4.3
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python-headless==4.5.5.62
    - packaging==21.3
    - pathspec==0.9.0
    - portalocker==2.3.2
    - protobuf==3.19.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pyparsing==3.0.6
    - pyyaml==6.0
    - regex==2022.1.18
    - requests==2.27.1
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - toml==0.10.2
    - tqdm==4.62.3
    - typed-ast==1.5.1
    - urllib3==1.26.8
    - werkzeug==2.0.2
    - yacs==0.1.8
    - zipp==3.7.0
